### ISSUE TITLE
sendDistributionMetric() syntax error using Lambda Layer

### ISSUE THREAD

**Issue by leeDav** [DataDog/datadog-lambda-layer-js#16]
## Expected Behavior
Using the example code from the Node section of [this page](https://docs.datadoghq.com/integrations/amazon_lambda/?tab=node#installing-and-using-the-datadog-layer). Removing the call to `sendDistributionMetric()` results in no syntax error.

## Actual Behavior
Syntax error is returned.

## Steps to Reproduce the Problem

  1. Use the [installing and using the DataDog layer](https://docs.datadoghq.com/integrations/amazon_lambda/?tab=node#installing-and-using-the-datadog-layer) example to create a new lambda with the `arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Node10-x:3` layer
  2. Set the `DD_API_KEY` env var
  3. Set the `DD_FORWARD_LOG` to `false`.

## Specifications

  - Datadog Lambda Layer version: 3
  - Node version: 10.x
  
## Stacktrace
  
```
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Unexpected token {",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token {",
    "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:36:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:776:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}
```

**Comment by DarcyRaynerDD** [comment]
We're going to take a look at reproducing this. My first thought is the docs page might have encoded a character somewhere to a non-ascii value, (like a quotation mark or something). Does typing the sendDistributionMetric line by hand work?

**Comment by pinkerton** [comment]
Hi @leeDav, can you provide the exact code you used? It'll help us hunt down the reported syntax error. Thanks!

**Comment by leeDav** [comment]
```js
import { datadog } from "datadog-lambda-js";
import { sendDistributionMetric } from "datadog-lambda-js";

async function myHandler(event, context) {
  sendDistributionMetric(
    "coffee_house.order_value", // Metric name
    12.45,                      // Metric value
    "product:latte",            // Associated tag
    "order:online",             // Another tag
  );
  return {
    statusCode: 200,
    body: "hello, dog!",
  };
}
// Wrap your handler function:
exports.exports.myHandler = datadog(myHandler);
```

Literally taken from the docs.

A colleague had it working, however, by changing all the `import`s to `require()`, which was very strange as I thought Node 10 to support ES6 imports :\

**Comment by pinkerton** [comment]
Ah, that should solve it. I'll go ahead and update our docs to reflect that. Thanks for catching this.

Do you have the Node 10 runtime selected for your Lambda? https://docs.aws.amazon.com/lambda/latest/dg/programming-model.html

**Comment by leeDav** [comment]
I do, thank you!

Apologies for the false alarm :)

**Comment by pinkerton** [comment]
No worries! Thank you for the report
