### ISSUE TITLE
Support Nodejs12.X

### ISSUE THREAD

**Issue by samuelAle** [DataDog/datadog-lambda-layer-js#42]
AWS supports nodejs 12.13.0
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

I'd like there to be a datadog lambda layer that is built for this runtime.

**Comment by pinkerton** [comment]
Hey @samuelAle, we actually just published this! https://docs.datadoghq.com/integrations/amazon_lambda/?tab=awsconsole#installing-and-using-the-datadog-lambda-layer

I see that it's not referenced in the README - will update that!
