### ISSUE TITLE
Ability to disable built-in tags for sendDistributionMetric function.

### ISSUE THREAD

**Issue by PatrykMilewski** [DataDog/datadog-lambda-layer-js#55]
## Expected Behavior

When I'm using NPM package `datadog-lambda-js` and I'm sending metrics using `function sendDistributionMetric(name: string, value: number, ...tags: string[]): void;` I end up receiving additional custom metrics with built-in tags, for example `dd_lambda_layer:datadog-nodev12.14.1`.

Since any unique combination of metric name and tag name is billed as separate custom metric, I would like to disable this behaviour, since I'm using `datadog-lambda-js` as DataDog API client for custom metrics.

## Actual Behavior

Calling `function sendDistributionMetric(name: string, value: number, ...tags: string[]): void;` from `datadog-lambda-js` NPM package adds additional, built-in tags, for example `dd_lambda_layer:datadog-nodev12.14.1`.

## Steps to Reproduce the Problem

  1. Create Node.js Lambda and add `"datadog-lambda-js": "2.17.0"` as dependency.
  2. Use `sendDistributionMetric` function.
  3. In DataDog UI, metrics explorer you will see some additional tags, that you haven't specified in the code.

## Specifications

  - Datadog Lambda Layer version: None, `"datadog-lambda-js": "2.17.0"`
  - Node version: 12.x

**Comment by pinkerton** [comment]
Hi @PatrykMilewski, thanks for filing an issue.

The custom metrics you submit with the Datadog Lambda Layer / package are Distribution metrics. These are unique in that you control which aggregations and percentiles you want. To disable a tag like `dd_lambda_layer`, you can navigate to Metrics > Distribution Metrics > `your.custom.metric` and change the aggregations there. 

Docs: https://docs.datadoghq.com/metrics/distributions/#customize-tagging

**Comment by PatrykMilewski** [comment]
Thank you @pinkerton, it worked!

**Comment by PatrykMilewski** [comment]
@pinkerton I think I have to reopen this issue. The workaround that you proposed works, but if I publish tens for metrics, then I have to click through them and for each of them disable `dd_lambda_layer` tag, which is time consuming and annoying.

My point is, that it could be avoided, since for my use case this tag is really not important and could be disabled, since I'm not getting any value of having it in my DataDog.

I did look into the code and it's only about possibility to force `getRuntimeTag()` to return nothing by some flag that can be provided with configuration.
```
export function sendDistributionMetric(name: string, value: number, ...tags: string[]) {
  tags = [...tags, getRuntimeTag()];

  if (currentMetricsListener !== undefined) {
    currentMetricsListener.sendDistributionMetric(name, value, ...tags);
  } else {
    logError("handler not initialized");
  }
}
```

**Comment by tianchu** [comment]
@PatrykMilewski I think this request makes sense, we can keep this issue open. 

However, to clarify, unless you emit the metric from multiple Lambda functions using different versions of Datadog layers, this extra tag won't increase # of billed custom metrics, as its cardinality is 1. Say, if the # of unique combinations of other tags is 12, then 12 * 1 is still 12. 

This doc might be helpful: https://docs.datadoghq.com/account_management/billing/custom_metrics/?tab=distribution

Let me know if I missed anything.

**Comment by PatrykMilewski** [comment]
@tianchu Thank you for response!

I thought that unique combinations of tags billing works a little bit different. Now I agree, that from biling perspective, there is no point in disabling this.

But still it adds some unneeded noise to all of the metrics.

Maybe let's keep this issue as open and if somebody else find it as a problem, then we can get back to it? 😄

**Comment by PatrykMilewski** [comment]
I no longer need of removing this default tag, that's why I'm closing this issue.
