### ISSUE TITLE
Additional metric types

### ISSUE THREAD

**Issue by Marigold** [DataDog/datadog-lambda-layer-js#56]
Is there any technical reason why is only the distribution metric implemented and not other like COUNT or HISTOGRAM? Using DISTRIBUTION is quite wasteful (i.e. it uses 5x more custom metrics) if I only need to count things.

**Comment by pinkerton** [comment]
Hi @Marigold, thanks for filing an issue. 

Histograms generate 5 custom metrics with 5 distinct metric names as shown here: https://docs.datadoghq.com/developers/metrics/types/?tab=histogram

But, those timeseries represent agent-aggregated values. Meanwhile, a distribution is logged under one metric name and represents the **global statistical distribution** of a set of values calculated across your entire distributed infrastructure in one time interval. This is especially applicable to serverless where we don't run an agent.

A distribution and a histogram generate the same number of custom metrics when tagged the same way. Docs: https://docs.datadoghq.com/account_management/billing/custom_metrics/?tab=histogram

**Comment by Marigold** [comment]
> This is especially applicable to serverless where we don't run an agent.

Thanks for explanation @pinkerton, that's what I've been missing and the reason we can't do it in serverless.
