### ISSUE TITLE
Allow set custom timestamp for metric datapoint

### ISSUE THREAD

**Issue by PatrykMilewski** [DataDog/datadog-lambda-layer-js#58]
## Expected Behavior

When I'm sending datapoint with `sendDistributionMetric` function, I would like to specify my custom timestamp.

## Actual Behavior

Right now it automatically uses the actual time for timestamp generation.

## Specifications

  - Datadog Lambda Layer version: none, datadog-lambda-layer-js:2.17.0
  - Node version: 12.x

**Comment by agocs** [comment]
👋 Hi, I've added this to a list of feature requests. Custom timestamps in this library make sense. We already allow them in Ruby, Python, and Go.

**Comment by PatrykMilewski** [comment]
@agocs Could you specify the header of the function, that would have this feature? I'm not sure how you are planning you API for this package, but if you guys would give me some hints, then I could implement it myself and create PR.

**Comment by agocs** [comment]
Hey @PatrykMilewski , I definitely appreciate the offer. I think the new function would take the signature

```
export function sendDistributionMetricWithDate(name: string, value: number, date: Date, ...tags: string[])
```

It would, unfortunately, require refactoring [`listener.sendDistrobutionMetric`](https://github.com/DataDog/datadog-lambda-layer-js/blob/master/src/metrics/listener.ts#L86) and a few other functions to accept the custom date.

**Comment by vishnuvisnu** [comment]
`public sendDistributionMetricWithDate(name: string, value: number, date: Date, ...tags: string[]) {
    if (this.config.logForwarding) {
      writeMetricToStdout(name, value, tags);
      return;
    }
    const dist = new Distribution(name, [{ timestamp: date, value }], ...tags);

    if (this.currentProcessor !== undefined) {
      this.currentProcessor.then((processor) => {
        processor.addMetric(dist);
      });
    } else {
      logError("can't send metrics, datadog lambda handler not set up.");
    }
}

public sendDistributionMetric(name: string, value: number, ...tags: string[]) {
  sendDistributionMetricWithDate(name, value, new Date(), tags);
}
`
These changes to MetricListener in listener.ts along with new function sendDistributionMetricWithDate in index.ts should work, right?

**Comment by vishnuvisnu** [comment]
@agocs This is the PR https://github.com/DataDog/datadog-lambda-layer-js/pull/63 I have created.

**Comment by vishnuvisnu** [comment]
@agocs Could you please expedite PR? We are currently using in datadog in production and using the datadog metrics from cloudwatch logs (that were published from the segment) that are in forming like MONITORING|..|..|..|.. but there is significant delay in getting metrics in datadog. This is the current ticket with the datadog team https://help.datadoghq.com/hc/en-us/requests/322610?flash_digest=9f923b6f7becc24b49af9543c88c5faa51c3a52c. Thanks.

**Comment by DarcyRaynerDD** [comment]
Hey @vishnuvisnu, thanks for the PR. I can review this for you.

**Comment by PatrykMilewski** [comment]
I'm closing it since PR #63 is already merged into master. Thank you @vishnuvisnu
