### ISSUE TITLE
No matching version found for serialize-error@true7.0.1

### ISSUE THREAD

**Issue by MehdiZonjy** [DataDog/datadog-lambda-layer-js#81]
## Expected Behavior
`npm install datadog-lambda-js` should work

## Actual Behavior
```
npm install datadog-lambda-js                                                                                                                     
npm ERR! code ETARGET
npm ERR! notarget No matching version found for serialize-error@true7.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'datadog-lambda-js'
npm ERR! notarget 
```
I think there is invalid depdency on `serialize-error` [Ref](https://github.com/DataDog/datadog-lambda-layer-js/blob/807f762e70eccf189e5e3e50938a62b464ae6bf7/package.json#L37)

```
    "serialize-error": "true7.0.1",
```
maybe this instead ?
```
    "serialize-error": "^7.0.1",
```

## Steps to Reproduce the Problem
1. `npm install datadog-lambda-js` 

## Specifications

  - Datadog Lambda Layer version: latest
  - Node version: v12.16.1

**Comment by sanketCactus** [comment]
Facing same issue.
@MehdiZonjy you are right !
it should be 
 `   "serialize-error": "^7.0.1",`
